@PROTOCOL = HTTP
@PROTOCOL_VERSION = 1.1
@HOSTNAME = localhost
@PORT = 5000
@CONTENT_TYPE_JSON = application/json
@CONTENT_TYPE_FORM = multipart/form-data
@PATH = user

###

GET {{PROTOCOL}}://{{HOSTNAME}}:{{PORT}}/{{PATH}} {{PROTOCOL}}/{{PROTOCOL_VERSION}}

###

POST {{PROTOCOL}}://{{HOSTNAME}}:{{PORT}}/{{PATH}}/avatar {{PROTOCOL}}/{{PROTOCOL_VERSION}}
Content-Length: 250
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarygi5jlGAbJYdfYWNE

------WebKitFormBoundarygi5jlGAbJYdfYWNE
Content-Disposition: form-data; name="file"; filename="img.png"
Content-Type: image/png

< ./img.png
------WebKitFormBoundarygi5jlGAbJYdfYWNE--

### "P@sswor12345"
POST {{PROTOCOL}}://{{HOSTNAME}}:{{PORT}}/{{PATH}} {{PROTOCOL}}/{{PROTOCOL_VERSION}}
Content-Type: {{CONTENT_TYPE_JSON}}

{
    "username": "juan_vicente_pradilla_1",
    "password": "42420aadbd62b2139fb611fd61113c88"
    "avatar": "/public/uploads/user/avatar/55a21e74-69cc-4dab-bbd5-a79cdfd12b64"

}

### 

POST {{PROTOCOL}}://{{HOSTNAME}}:{{PORT}}/{{PATH}}/login {{PROTOCOL}}/{{PROTOCOL_VERSION}}
Content-Type: {{CONTENT_TYPE_JSON}}

{
    "username": "juan_vicente_pradilla_1",
    "password": "42420aadbd62b2139fb611fd61113c88"
}